<aside class="dashboard-sidebar no-print admin-sidebar-card w-72 h-screen sticky top-0 left-0 flex-shrink-0 bg-white flex flex-col border-r border-gray-200" role="navigation" aria-label="Administrator portal navigation">
    <div class="px-4 pt-4 pb-3 flex flex-col flex-1 min-h-0">
        <div class="border-b border-gray-200 pb-3 mb-10 flex items-center gap-3 shrink-0">
            <img src="{{ asset('images/logo.png') }}" alt="DCOMC" class="h-16 w-auto object-contain shrink-0" onerror="this.style.display='none'">
            <span class="font-bold text-[#1E40AF] text-base leading-tight font-heading">DCOMC Administrator Portal</span>
        </div>
        <div class="flex-1 min-h-0 overflow-y-auto">
            <nav class="flex flex-col space-y-1 pt-8">
                <a href="{{ route('admin.dashboard') }}" class="block flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm no-underline border-l-4 border-transparent transition-colors {{ request()->routeIs('admin.dashboard') ? 'bg-[#1E40AF] text-white border-[#1E40AF]' : 'text-gray-700 hover:bg-blue-50 hover:border-[#1E40AF]' }}" style="font-family: 'Roboto', sans-serif;">
                    <svg class="w-4 h-4 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"/></svg>
                    Dashboard
                </a>
                <a href="{{ route('admin.accounts') }}" class="block flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm no-underline border-l-4 border-transparent transition-colors {{ request()->routeIs('admin.accounts') ? 'bg-[#1E40AF] text-white border-[#1E40AF]' : 'text-gray-700 hover:bg-blue-50 hover:border-[#1E40AF]' }}" style="font-family: 'Roboto', sans-serif;">
                    <svg class="w-4 h-4 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z"/></svg>
                    Accounts
                </a>
                <a href="{{ route('admin.feedback.index') }}" class="block flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm no-underline border-l-4 border-transparent transition-colors {{ request()->routeIs('admin.feedback.*') ? 'bg-[#1E40AF] text-white border-[#1E40AF]' : 'text-gray-700 hover:bg-blue-50 hover:border-[#1E40AF]' }}" style="font-family: 'Roboto', sans-serif;">
                    <svg class="w-4 h-4 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z"/></svg>
                    Feedback
                </a>
                <div class="mt-6">
                    <p class="px-4 py-1.5 text-xs font-bold uppercase tracking-wide text-gray-500 mb-0.5" style="font-family: 'Figtree', sans-serif;">System</p>
                    <details class="rounded" {{ request()->routeIs('admin.system.*') || request()->routeIs('admin.audit-logs.*') || request()->routeIs('admin.activity-logs.*') ? 'open' : '' }}>
                        <summary class="block flex items-center gap-2 px-4 py-2.5 rounded-lg cursor-pointer list-none text-gray-700 hover:bg-blue-50 border-l-4 border-transparent hover:border-[#1E40AF] transition-colors text-sm" style="font-family: 'Roboto', sans-serif;">
                            <svg class="w-4 h-4 shrink-0 text-[#1E40AF]" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z"/><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/></svg>
                            <span class="flex-1">System</span><svg class="w-4 h-4 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"/></svg>
                        </summary>
                        <div class="space-y-1 pl-2 mt-0.5">
                            <a href="{{ route('admin.system.overview') }}" class="block flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm no-underline border-l-4 border-transparent transition-colors {{ request()->routeIs('admin.system.overview') ? 'bg-[#1E40AF] text-white border-[#1E40AF]' : 'text-gray-700 hover:bg-blue-50 hover:border-[#1E40AF]' }}" style="font-family: 'Roboto', sans-serif;">Overview</a>
                            <a href="{{ route('admin.system.backup') }}" class="block flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm no-underline border-l-4 border-transparent transition-colors {{ request()->routeIs('admin.system.backup') ? 'bg-[#1E40AF] text-white border-[#1E40AF]' : 'text-gray-700 hover:bg-blue-50 hover:border-[#1E40AF]' }}" style="font-family: 'Roboto', sans-serif;">Backup</a>
                            <a href="{{ route('admin.system.logs') }}" class="block flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm no-underline border-l-4 border-transparent transition-colors {{ request()->routeIs('admin.system.logs') ? 'bg-[#1E40AF] text-white border-[#1E40AF]' : 'text-gray-700 hover:bg-blue-50 hover:border-[#1E40AF]' }}" style="font-family: 'Roboto', sans-serif;">Application logs</a>
                            <a href="{{ route('admin.system.failed-jobs') }}" class="block flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm no-underline border-l-4 border-transparent transition-colors {{ request()->routeIs('admin.system.failed-jobs') ? 'bg-[#1E40AF] text-white border-[#1E40AF]' : 'text-gray-700 hover:bg-blue-50 hover:border-[#1E40AF]' }}" style="font-family: 'Roboto', sans-serif;">Failed jobs</a>
                            <a href="{{ route('admin.system.maintenance') }}" class="block flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm no-underline border-l-4 border-transparent transition-colors {{ request()->routeIs('admin.system.maintenance') ? 'bg-[#1E40AF] text-white border-[#1E40AF]' : 'text-gray-700 hover:bg-blue-50 hover:border-[#1E40AF]' }}" style="font-family: 'Roboto', sans-serif;">Maintenance mode</a>
                            <a href="{{ route('admin.system.editor') }}" class="block flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm no-underline border-l-4 border-transparent transition-colors {{ request()->routeIs('admin.system.editor') ? 'bg-[#1E40AF] text-white border-[#1E40AF]' : 'text-gray-700 hover:bg-blue-50 hover:border-[#1E40AF]' }}" style="font-family: 'Roboto', sans-serif;">Compiler</a>
                            <a href="{{ route('admin.activity-logs.index') }}" class="block flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm no-underline border-l-4 border-transparent transition-colors {{ request()->routeIs('admin.activity-logs.*') ? 'bg-[#1E40AF] text-white border-[#1E40AF]' : 'text-gray-700 hover:bg-blue-50 hover:border-[#1E40AF]' }}" style="font-family: 'Roboto', sans-serif;">Activity log</a>
                            <a href="{{ route('admin.audit-logs.index') }}" class="block flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm no-underline border-l-4 border-transparent transition-colors {{ request()->routeIs('admin.audit-logs.*') ? 'bg-[#1E40AF] text-white border-[#1E40AF]' : 'text-gray-700 hover:bg-blue-50 hover:border-[#1E40AF]' }}" style="font-family: 'Roboto', sans-serif;">Audit log</a>
                        </div>
                    </details>
                </div>
                <div class="mt-6">
                    <p class="px-4 py-1.5 text-xs font-bold uppercase tracking-wide text-gray-500 mb-0.5" style="font-family: 'Figtree', sans-serif;">Reports</p>
                    <details class="rounded" {{ request()->routeIs('admin.analytics*') || request()->routeIs('admin.reports') ? 'open' : '' }}>
                        <summary class="block flex items-center gap-2 px-4 py-2.5 rounded-lg cursor-pointer list-none text-gray-700 hover:bg-blue-50 border-l-4 border-transparent hover:border-[#1E40AF] transition-colors text-sm" style="font-family: 'Roboto', sans-serif;">
                            <svg class="w-4 h-4 shrink-0 text-[#1E40AF]" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"/></svg>
                            <span class="flex-1">Reports</span><svg class="w-4 h-4 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"/></svg>
                        </summary>
                        <div class="space-y-1 pl-2 mt-0.5">
                            <a href="{{ route('admin.analytics') }}" class="block flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm no-underline border-l-4 border-transparent transition-colors {{ request()->routeIs('admin.analytics*') ? 'bg-[#1E40AF] text-white border-[#1E40AF]' : 'text-gray-700 hover:bg-blue-50 hover:border-[#1E40AF]' }}" style="font-family: 'Roboto', sans-serif;">Analytics</a>
                            <a href="{{ route('admin.reports') }}" class="block flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm no-underline border-l-4 border-transparent transition-colors {{ request()->routeIs('admin.reports') ? 'bg-[#1E40AF] text-white border-[#1E40AF]' : 'text-gray-700 hover:bg-blue-50 hover:border-[#1E40AF]' }}" style="font-family: 'Roboto', sans-serif;">Reports</a>
                        </div>
                    </details>
                </div>
                <div class="mt-6">
                    <p class="px-4 py-1.5 text-xs font-bold uppercase tracking-wide text-gray-500 mb-0.5" style="font-family: 'Figtree', sans-serif;">Settings</p>
                    <details class="rounded" {{ request()->routeIs('admin.settings.*') ? 'open' : '' }}>
                        <summary class="block flex items-center gap-2 px-4 py-2.5 rounded-lg cursor-pointer list-none text-gray-700 hover:bg-blue-50 border-l-4 border-transparent hover:border-[#1E40AF] transition-colors text-sm" style="font-family: 'Roboto', sans-serif;">
                            <svg class="w-4 h-4 shrink-0 text-[#1E40AF]" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6V4m0 2a2 2 0 100 4m0-4a2 2 0 110 4m-6 8a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4m6 6v10m6-2a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4"/></svg>
                            <span class="flex-1">Settings</span><svg class="w-4 h-4 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"/></svg>
                        </summary>
                        <div class="space-y-1 pl-2 mt-0.5">
                            <a href="{{ route('admin.settings.school-years') }}" class="block flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm no-underline border-l-4 border-transparent transition-colors {{ request()->routeIs('admin.settings.school-years') ? 'bg-[#1E40AF] text-white border-[#1E40AF]' : 'text-gray-700 hover:bg-blue-50 hover:border-[#1E40AF]' }}" style="font-family: 'Roboto', sans-serif;">School Years</a>
                            <a href="{{ route('admin.settings.semesters') }}" class="block flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm no-underline border-l-4 border-transparent transition-colors {{ request()->routeIs('admin.settings.semesters') ? 'bg-[#1E40AF] text-white border-[#1E40AF]' : 'text-gray-700 hover:bg-blue-50 hover:border-[#1E40AF]' }}" style="font-family: 'Roboto', sans-serif;">Semesters</a>
                            <a href="{{ route('admin.settings.year-levels') }}" class="block flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm no-underline border-l-4 border-transparent transition-colors {{ request()->routeIs('admin.settings.year-levels') ? 'bg-[#1E40AF] text-white border-[#1E40AF]' : 'text-gray-700 hover:bg-blue-50 hover:border-[#1E40AF]' }}" style="font-family: 'Roboto', sans-serif;">Year Levels</a>
                            <a href="{{ route('admin.settings.blocks') }}" class="block flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm no-underline border-l-4 border-transparent transition-colors {{ request()->routeIs('admin.settings.blocks') ? 'bg-[#1E40AF] text-white border-[#1E40AF]' : 'text-gray-700 hover:bg-blue-50 hover:border-[#1E40AF]' }}" style="font-family: 'Roboto', sans-serif;">Blocks</a>
                            <a href="{{ route('admin.settings.subjects') }}" class="block flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm no-underline border-l-4 border-transparent transition-colors {{ request()->routeIs('admin.settings.subjects') ? 'bg-[#1E40AF] text-white border-[#1E40AF]' : 'text-gray-700 hover:bg-blue-50 hover:border-[#1E40AF]' }}" style="font-family: 'Roboto', sans-serif;">Subjects</a>
                            <a href="{{ route('admin.settings.fees') }}" class="block flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm no-underline border-l-4 border-transparent transition-colors {{ request()->routeIs('admin.settings.fees') ? 'bg-[#1E40AF] text-white border-[#1E40AF]' : 'text-gray-700 hover:bg-blue-50 hover:border-[#1E40AF]' }}" style="font-family: 'Roboto', sans-serif;">Fees</a>
                            <a href="{{ route('admin.settings.professors') }}" class="block flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm no-underline border-l-4 border-transparent transition-colors {{ request()->routeIs('admin.settings.professors') ? 'bg-[#1E40AF] text-white border-[#1E40AF]' : 'text-gray-700 hover:bg-blue-50 hover:border-[#1E40AF]' }}" style="font-family: 'Roboto', sans-serif;">Professors</a>
                            <a href="{{ route('admin.settings.rooms') }}" class="block flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm no-underline border-l-4 border-transparent transition-colors {{ request()->routeIs('admin.settings.rooms') ? 'bg-[#1E40AF] text-white border-[#1E40AF]' : 'text-gray-700 hover:bg-blue-50 hover:border-[#1E40AF]' }}" style="font-family: 'Roboto', sans-serif;">Rooms</a>
                            <a href="{{ route('admin.settings.cor-scopes.index') }}" class="block flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm no-underline border-l-4 border-transparent transition-colors {{ request()->routeIs('admin.settings.cor-scopes.*') ? 'bg-[#1E40AF] text-white border-[#1E40AF]' : 'text-gray-700 hover:bg-blue-50 hover:border-[#1E40AF]' }}" style="font-family: 'Roboto', sans-serif;">COR Scopes</a>
                            <a href="{{ route('admin.settings.staff-access') }}" class="block flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm no-underline border-l-4 border-transparent transition-colors {{ request()->routeIs('admin.settings.staff-access') ? 'bg-[#1E40AF] text-white border-[#1E40AF]' : 'text-gray-700 hover:bg-blue-50 hover:border-[#1E40AF]' }}" style="font-family: 'Roboto', sans-serif;">Staff access</a>
                            <a href="{{ route('admin.settings.registrar-access') }}" class="block flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm no-underline border-l-4 border-transparent transition-colors {{ request()->routeIs('admin.settings.registrar-access') ? 'bg-[#1E40AF] text-white border-[#1E40AF]' : 'text-gray-700 hover:bg-blue-50 hover:border-[#1E40AF]' }}" style="font-family: 'Roboto', sans-serif;">Registrar access</a>
                            <a href="{{ route('admin.settings.unifast-access') }}" class="block flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm no-underline border-l-4 border-transparent transition-colors {{ request()->routeIs('admin.settings.unifast-access') ? 'bg-[#1E40AF] text-white border-[#1E40AF]' : 'text-gray-700 hover:bg-blue-50 hover:border-[#1E40AF]' }}" style="font-family: 'Roboto', sans-serif;">UniFAST access</a>
                        </div>
                    </details>
                </div>
            </nav>
        </div>
        <div class="mt-auto pt-3 border-t border-gray-200 shrink-0">
            <a href="{{ route('admin.feedback.create') }}" class="block flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm no-underline border-l-4 border-transparent transition-colors text-gray-700 hover:bg-blue-50 hover:border-[#1E40AF]" style="font-family: 'Roboto', sans-serif;">
                <svg class="w-4 h-4 shrink-0 text-[#1E40AF]" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z"/></svg>
                Send feedback
            </a>
            <form method="POST" action="{{ route('logout') }}" class="mt-1.5">
                @csrf
                <button type="submit" class="w-full py-2.5 px-3 rounded-lg text-sm font-medium text-white bg-red-600 hover:bg-red-700 transition-colors" style="font-family: 'Roboto', sans-serif;">Log Out</button>
            </form>
        </div>
    </div>
</aside>
